name: Trigger merge request

on:
  workflow_dispatch:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: write

jobs:
  fix-linting:
    name: PR Merge
    uses: khulnasoft-lab/workflows/.github/workflows/auto-merge.yml@main
    secrets: inherit
